params:
  seed: ${...seed}

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: transformer
    space:
      continuous:

    transformer:
      input_split: [24, 24, 24, 7, 3, 3, 7, 4, 65, 30, 20]
      seq_pool: True
      embedding_dim: 256
      num_layers: 4
      num_heads: 2
      mlp_ratio: 1.0
      dropout: 0.0
      attention_dropout: 0.0
      stochastic_depth: 0.0
      positional_embedding: 'none'

  load_checkpoint: ${if:${...checkpoint},True,False} # flag which sets whether to load the checkpoint
  load_path: ${...checkpoint} # path to the checkpoint to load

  config:
    name: ${resolve_default:ShadowHand,${....experiment}}
    full_experiment_name: ${.name}
    env_name: rlgpu
    multi_gpu: False
    ppo: True
    mixed_precision: False
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 0.01
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 5e-4
    lr_schedule: None #adaptive
    schedule_type: standard
    kl_threshold: 0.016
    score_to_win: 100000
    max_epochs: ${resolve_default:5000,${....max_iterations}}
    save_best_after: 500
    save_frequency: 200
    print_stats: True
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 8
    minibatch_size: 8192
    mini_epochs: 5
    critic_coef: 4
    clip_value: True
    seq_len: 4
    bounds_loss_coef: 0.0001
    weight_decay: 0.001
    player:
      #render: True
      deterministic: True
      games_num: 100000
      print_stats: True